spring:
  application:
    name: store-inscricao
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/store}
    username: ${DATABASE_USERNAME:store}
    password: ${DATABASE_PASSWORD:store123321}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: inscricao
  jpa:
    properties:
      hibernate:
        default_schema: inscricao
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
management:
  endpoints:
    web:
      base-path: /inscricoes/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

springdoc:
  api-docs:
    path: /inscricoes/v3/api-docs
  swagger-ui:
    path: /inscricoes/swagger-ui.html